import java_cup.runtime.*;

action code {:
    TablaSimbolos tab = new TablaSimbolos();
:}

parser code {:
    public void syntax_error(Symbol s){
        System.out.println("Error de sintaxis: "+ s.value +" Línea "+(s.left)+" Columna "+(s.right) );
    }
    public void unrecovered_syntax_error(Symbol s) throws Exception {
        Symbol t = getScanner().next_token();
    }
:}
scan with {:
  return getScanner().next_token();
:};



/* ===== terminales ===== */
terminal SUMA;
terminal RESTA;
terminal MULTIPLICACION;
terminal DIVISION;
terminal DIVISION_ENTERA;
terminal MODULO;
terminal POTENCIA;
terminal AUMENTO;
terminal DISMINUCION;
terminal BLOQUE_A;
terminal BLOQUE_C;
terminal PARENTESIS_A;
terminal PARENTESIS_B;
terminal LLAVE_B;
terminal LLAVE_A;
terminal COMA;
terminal FLECHA;
terminal ASIGNAR;
terminal MAYOR;
terminal MENOR;
terminal IGUAL;
terminal DIFERENTE;
terminal MAYOR_IGUAL;
terminal MENOR_IGUAL;   
terminal AND;
terminal OR;
terminal NOT;
terminal WORD;
terminal LOCAL;
terminal GIFT;
terminal NAVIDAD;
terminal COAL;
terminal INT;
terminal FLOAT;
terminal BOOLEAN;
terminal CHAR;
terminal STRING;
terminal DECIDE;
terminal OF;
terminal ELSE;
terminal END;
terminal LOOP;
terminal EXIT;
terminal WHEN;
terminal FOR;
terminal RETURN;
terminal BREAK;
terminal SHOW;
terminal GET;
terminal ENDL;
terminal INT_LITERAL;
terminal FLOAT_LITERAL;
terminal STRING_LITERAL;
terminal CHAR_LITERAL;
terminal BOOLEAN_LITERAL;
terminal IDENTIFICADOR;




/* ===== No terminales ===== */
non terminal Nodo programa;
non terminal Nodo funciones;
non terminal Nodo globales;
non terminal Nodo global;
non terminal Nodo main;
non terminal Nodo funcion;
non terminal Nodo params;
non terminal Nodo tipo;
non terminal Nodo literal;
non terminal Nodo creacion;
non terminal Nodo asignacion;
non terminal Nodo sentencia;
non terminal Nodo condiciones;
non terminal Nodo condicion;
non terminal Nodo else_opcional;
non terminal Nodo sentencias;
non terminal Nodo bloque;
non terminal Nodo expr;
non terminal Nodo Arreglo;
non terminal Nodo BloqueArreglo;
non terminal Nodo itemParams;
non terminal Nodo Columnas;
non terminal Nodo filas;
non terminal Nodo L_elementos;
non terminal inicio

/* ===== Precedencias ===== */
precedence left SUMA, RESTA;
precedence left MULTIPLICACION;
precedence left DIVISION;
precedence left DIVISION_ENTERA;
precedence left MODULO;
precedence right POTENCIA;
precedence left OR;
precedence left AND;
precedence nonassoc MAYOR, MENOR, IGUAL, DIFERENTE, MAYOR_IGUAL, MENOR_IGUAL;


inicio::= programa{:
    System.out.println("=== TABLA DE SÍMBOLOS GLOBAL ===");
    tab.printGlobalTable();
    System.out.println("\n\n Arbol sintactico:");
    ((Nodo)programa).arbol();
:}


programa ::= globales funciones main ;

globales ::= globales global | /* vacío */ ;

global ::= WORD tipo IDENTIFICADOR ENDL
         | WORD tipo IDENTIFICADOR ASIGNAR expr ENDL 
         |  WORD tipo IDENTIFICADOR Arreglo | WORD tipo IDENTIFICADOR Arreglo ASIGNAR BloqueArreglo ;

main ::= COAL NAVIDAD PARENTESIS_A PARENTESIS_B bloque ;

funciones ::= funcion | funciones funcion ;

funcion ::= GIFT tipo IDENTIFICADOR params bloque ;

params ::= PARENTESIS_A PARENTESIS_B | PARENTESIS_A itemParams PARENTESIS_B ;

itemParams ::= tipo IDENTIFICADOR | itemParams COMA tipo IDENTIFICADOR ;

tipo ::= INT  {: Nodo result = new Nodo("int");     result.setTipo("int");     RESULT=result; :}
    | FLOAT   {: Nodo result = new Nodo("float");   result.setTipo("float");   RESULT=result; :}
    | STRING  {: Nodo result = new Nodo("string");  result.setTipo("string");  RESULT=result; :}
    | BOOLEAN {: Nodo result = new Nodo("boolean"); result.setTipo("boolean"); RESULT=result; :}
    | CHAR    {: Nodo result = new Nodo("char");    result.setTipo("char");    RESULT=result; :}
;

literal ::= INT_LITERAL:result    {: RESULT = result.value; :}
    | FLOAT_LITERAL:result   {: RESULT = result.value; :}
    | STRING_LITERAL:result  {: RESULT = result.value; :}
    | CHAR_LITERAL:result    {: RESULT = result.value; :}
    | BOOLEAN_LITERAL:result {: RESULT = result.value; :}
;
creacion ::= LOCAL tipo IDENTIFICADOR ENDL | LOCAL tipo IDENTIFICADOR ASIGNAR expr ENDL | LOCAL tipo IDENTIFICADOR Arreglo ENDL | LOCAL tipo IDENTIFICADOR Arreglo ASIGNAR BloqueArreglo ENDL;

asignacion ::= IDENTIFICADOR ASIGNAR expr ENDL ;

//revisar esta parte 
sentencia ::= creacion
            | asignacion
            | expr ENDL
            | DECIDE OF condiciones else_opcional END DECIDE ENDL
            | LOOP sentencias EXIT WHEN expr ENDL END LOOP ENDL
            | FOR PARENTESIS_A asignacion expr ENDL expr PARENTESIS_B bloque
            | RETURN expr ENDL
            | BREAK ENDL
            | SHOW expr ENDL
            | GET expr ENDL
            ;

//para poder tener varias condiciones completas
condiciones ::= condicion | condiciones condicion ;

condicion ::= expr FLECHA bloque ;

//se pide el else opcional, por lo que se pone /* vacio */
else_opcional ::= /* vacio */| ELSE FLECHA bloque ;

sentencias ::=  /* vacio */| sentencias sentencia ;

bloque ::= BLOQUE_A sentencias BLOQUE_C ;

expr ::= expr SUMA expr
       | expr RESTA expr
       | expr MULTIPLICACION expr
       | expr DIVISION expr
       | expr DIVISION_ENTERA expr
       | expr MODULO expr
       | expr POTENCIA expr
       | expr MAYOR expr
       | expr MENOR expr
       | expr IGUAL expr
       | expr DIFERENTE expr
       | expr MAYOR_IGUAL expr
       | expr MENOR_IGUAL expr
       | expr AND expr
       | expr OR expr
       | NOT expr
       | AUMENTO IDENTIFICADOR
       | DISMINUCION IDENTIFICADOR
       | PARENTESIS_A expr PARENTESIS_B
       | literal
       | IDENTIFICADOR
       ;

Arreglo ::=LLAVE_A INT_LITERAL LLAVE_B LLAVE_A INT_LITERAL LLAVE_B ;
BloqueArreglo ::= BLOQUE_A Columnas BLOQUE_C;
Columnas ::= Columnas COMA filas | filas ;
filas ::= BLOQUE_A L_elementos BLOQUE_C ;
L_elementos ::= L_elementos COMA literal | literal;
