
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\115\000\002\002\005\000\002\002\004\000\002\004" +
    "\004\000\002\004\002\000\002\005\006\000\002\005\010" +
    "\000\002\005\006\000\002\005\010\000\002\006\007\000" +
    "\002\003\003\000\002\003\004\000\002\007\007\000\002" +
    "\010\004\000\002\010\005\000\002\026\004\000\002\026" +
    "\006\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\011\003\000\002\011\003\000\002\012\003\000" +
    "\002\012\003\000\002\012\003\000\002\012\003\000\002" +
    "\012\003\000\002\013\006\000\002\013\010\000\002\013" +
    "\007\000\002\013\011\000\002\014\006\000\002\015\003" +
    "\000\002\015\003\000\002\015\004\000\002\015\011\000" +
    "\002\015\013\000\002\015\012\000\002\015\005\000\002" +
    "\015\004\000\002\015\005\000\002\015\005\000\002\016" +
    "\003\000\002\016\004\000\002\017\005\000\002\020\002" +
    "\000\002\020\005\000\002\021\002\000\002\021\004\000" +
    "\002\022\005\000\002\023\005\000\002\023\005\000\002" +
    "\023\005\000\002\023\005\000\002\023\005\000\002\023" +
    "\005\000\002\023\005\000\002\023\005\000\002\023\005" +
    "\000\002\023\005\000\002\023\005\000\002\023\005\000" +
    "\002\023\005\000\002\023\005\000\002\023\005\000\002" +
    "\023\004\000\002\023\004\000\002\023\004\000\002\023" +
    "\005\000\002\023\003\000\002\023\003\000\002\024\010" +
    "\000\002\025\005\000\002\027\005\000\002\027\003\000" +
    "\002\030\005\000\002\031\005\000\002\031\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\257\000\006\037\ufffe\041\ufffe\001\002\000\004\002" +
    "\261\001\002\000\006\037\007\041\006\001\002\000\014" +
    "\044\163\045\161\046\160\047\162\050\156\001\002\000" +
    "\014\044\163\045\161\046\160\047\162\050\156\001\002" +
    "\000\006\037\uffff\041\uffff\001\002\000\006\041\ufff8\043" +
    "\ufff8\001\002\000\006\041\006\043\015\001\002\000\004" +
    "\002\001\001\002\000\006\041\ufff7\043\ufff7\001\002\000" +
    "\004\042\016\001\002\000\004\017\017\001\002\000\004" +
    "\020\020\001\002\000\004\015\021\001\002\000\050\013" +
    "\uffd3\014\uffd3\016\uffd3\017\uffd3\036\uffd3\040\uffd3\051\uffd3" +
    "\055\uffd3\060\uffd3\061\uffd3\062\uffd3\063\uffd3\064\uffd3\066" +
    "\uffd3\067\uffd3\070\uffd3\071\uffd3\072\uffd3\073\uffd3\001\002" +
    "\000\004\002\ufff9\001\002\000\050\013\035\014\052\016" +
    "\047\017\044\036\030\040\027\051\033\055\025\060\050" +
    "\061\032\062\042\063\026\064\053\066\036\067\051\070" +
    "\037\071\043\072\031\073\045\001\002\000\042\004\060" +
    "\005\071\006\063\007\067\010\070\011\066\012\057\026" +
    "\064\027\061\030\065\031\072\032\062\033\073\034\056" +
    "\035\074\065\232\001\002\000\050\013\uffd3\014\uffd3\017" +
    "\uffd3\036\uffd3\040\uffd3\051\uffd3\055\uffd3\056\uffd3\060\uffd3" +
    "\061\uffd3\062\uffd3\063\uffd3\064\uffd3\066\uffd3\067\uffd3\070" +
    "\uffd3\071\uffd3\072\uffd3\073\uffd3\001\002\000\026\013\035" +
    "\014\052\017\044\036\030\066\036\067\051\070\037\071" +
    "\043\072\031\073\055\001\002\000\014\044\163\045\161" +
    "\046\160\047\162\050\156\001\002\000\026\013\035\014" +
    "\052\017\044\036\030\066\036\067\051\070\037\071\043" +
    "\072\031\073\055\001\002\000\052\004\uffe8\005\uffe8\006" +
    "\uffe8\007\uffe8\010\uffe8\011\uffe8\012\uffe8\016\uffe8\020\uffe8" +
    "\023\uffe8\024\uffe8\026\uffe8\027\uffe8\030\uffe8\031\uffe8\032" +
    "\uffe8\033\uffe8\034\uffe8\035\uffe8\065\uffe8\001\002\000\026" +
    "\013\035\014\052\017\044\036\030\066\036\067\051\070" +
    "\037\071\043\072\031\073\055\001\002\000\004\052\135" +
    "\001\002\000\052\013\uffe1\014\uffe1\016\uffe1\017\uffe1\036" +
    "\uffe1\040\uffe1\051\uffe1\055\uffe1\056\uffe1\060\uffe1\061\uffe1" +
    "\062\uffe1\063\uffe1\064\uffe1\066\uffe1\067\uffe1\070\uffe1\071" +
    "\uffe1\072\uffe1\073\uffe1\001\002\000\004\073\134\001\002" +
    "\000\052\004\uffec\005\uffec\006\uffec\007\uffec\010\uffec\011" +
    "\uffec\012\uffec\016\uffec\020\uffec\023\uffec\024\uffec\026\uffec" +
    "\027\uffec\030\uffec\031\uffec\032\uffec\033\uffec\034\uffec\035" +
    "\uffec\065\uffec\001\002\000\052\004\uffea\005\uffea\006\uffea" +
    "\007\uffea\010\uffea\011\uffea\012\uffea\016\uffea\020\uffea\023" +
    "\uffea\024\uffea\026\uffea\027\uffea\030\uffea\031\uffea\032\uffea" +
    "\033\uffea\034\uffea\035\uffea\065\uffea\001\002\000\052\013" +
    "\uffd2\014\uffd2\016\uffd2\017\uffd2\036\uffd2\040\uffd2\051\uffd2" +
    "\055\uffd2\056\uffd2\060\uffd2\061\uffd2\062\uffd2\063\uffd2\064" +
    "\uffd2\066\uffd2\067\uffd2\070\uffd2\071\uffd2\072\uffd2\073\uffd2" +
    "\001\002\000\052\013\uffe2\014\uffe2\016\uffe2\017\uffe2\036" +
    "\uffe2\040\uffe2\051\uffe2\055\uffe2\056\uffe2\060\uffe2\061\uffe2" +
    "\062\uffe2\063\uffe2\064\uffe2\066\uffe2\067\uffe2\070\uffe2\071" +
    "\uffe2\072\uffe2\073\uffe2\001\002\000\004\065\133\001\002" +
    "\000\052\004\uffe9\005\uffe9\006\uffe9\007\uffe9\010\uffe9\011" +
    "\uffe9\012\uffe9\016\uffe9\020\uffe9\023\uffe9\024\uffe9\026\uffe9" +
    "\027\uffe9\030\uffe9\031\uffe9\032\uffe9\033\uffe9\034\uffe9\035" +
    "\uffe9\065\uffe9\001\002\000\026\013\035\014\052\017\044" +
    "\036\030\066\036\067\051\070\037\071\043\072\031\073" +
    "\055\001\002\000\044\004\uffbc\005\uffbc\006\uffbc\007\uffbc" +
    "\010\uffbc\011\uffbc\012\uffbc\025\126\026\uffbc\027\uffbc\030" +
    "\uffbc\031\uffbc\032\uffbc\033\uffbc\034\uffbc\035\uffbc\065\uffbc" +
    "\001\002\000\046\004\uffbd\005\uffbd\006\uffbd\007\uffbd\010" +
    "\uffbd\011\uffbd\012\uffbd\020\uffbd\024\uffbd\026\uffbd\027\uffbd" +
    "\030\uffbd\031\uffbd\032\uffbd\033\uffbd\034\uffbd\035\uffbd\065" +
    "\uffbd\001\002\000\064\002\uffd1\013\uffd1\014\uffd1\016\uffd1" +
    "\017\uffd1\036\uffd1\040\uffd1\041\uffd1\043\uffd1\051\uffd1\053" +
    "\uffd1\054\uffd1\055\uffd1\056\uffd1\060\uffd1\061\uffd1\062\uffd1" +
    "\063\uffd1\064\uffd1\066\uffd1\067\uffd1\070\uffd1\071\uffd1\072" +
    "\uffd1\073\uffd1\001\002\000\004\017\116\001\002\000\052" +
    "\004\uffeb\005\uffeb\006\uffeb\007\uffeb\010\uffeb\011\uffeb\012" +
    "\uffeb\016\uffeb\020\uffeb\023\uffeb\024\uffeb\026\uffeb\027\uffeb" +
    "\030\uffeb\031\uffeb\032\uffeb\033\uffeb\034\uffeb\035\uffeb\065" +
    "\uffeb\001\002\000\004\073\115\001\002\000\026\013\035" +
    "\014\052\017\044\036\030\066\036\067\051\070\037\071" +
    "\043\072\031\073\055\001\002\000\042\004\060\005\071" +
    "\006\063\007\067\010\070\011\066\012\057\026\064\027" +
    "\061\030\065\031\072\032\062\033\073\034\056\035\074" +
    "\065\075\001\002\000\046\004\uffbc\005\uffbc\006\uffbc\007" +
    "\uffbc\010\uffbc\011\uffbc\012\uffbc\020\uffbc\024\uffbc\026\uffbc" +
    "\027\uffbc\030\uffbc\031\uffbc\032\uffbc\033\uffbc\034\uffbc\035" +
    "\uffbc\065\uffbc\001\002\000\026\013\035\014\052\017\044" +
    "\036\030\066\036\067\051\070\037\071\043\072\031\073" +
    "\055\001\002\000\026\013\035\014\052\017\044\036\030" +
    "\066\036\067\051\070\037\071\043\072\031\073\055\001" +
    "\002\000\026\013\035\014\052\017\044\036\030\066\036" +
    "\067\051\070\037\071\043\072\031\073\055\001\002\000" +
    "\026\013\035\014\052\017\044\036\030\066\036\067\051" +
    "\070\037\071\043\072\031\073\055\001\002\000\026\013" +
    "\035\014\052\017\044\036\030\066\036\067\051\070\037" +
    "\071\043\072\031\073\055\001\002\000\026\013\035\014" +
    "\052\017\044\036\030\066\036\067\051\070\037\071\043" +
    "\072\031\073\055\001\002\000\026\013\035\014\052\017" +
    "\044\036\030\066\036\067\051\070\037\071\043\072\031" +
    "\073\055\001\002\000\026\013\035\014\052\017\044\036" +
    "\030\066\036\067\051\070\037\071\043\072\031\073\055" +
    "\001\002\000\026\013\035\014\052\017\044\036\030\066" +
    "\036\067\051\070\037\071\043\072\031\073\055\001\002" +
    "\000\026\013\035\014\052\017\044\036\030\066\036\067" +
    "\051\070\037\071\043\072\031\073\055\001\002\000\026" +
    "\013\035\014\052\017\044\036\030\066\036\067\051\070" +
    "\037\071\043\072\031\073\055\001\002\000\026\013\035" +
    "\014\052\017\044\036\030\066\036\067\051\070\037\071" +
    "\043\072\031\073\055\001\002\000\026\013\035\014\052" +
    "\017\044\036\030\066\036\067\051\070\037\071\043\072" +
    "\031\073\055\001\002\000\026\013\035\014\052\017\044" +
    "\036\030\066\036\067\051\070\037\071\043\072\031\073" +
    "\055\001\002\000\026\013\035\014\052\017\044\036\030" +
    "\066\036\067\051\070\037\071\043\072\031\073\055\001" +
    "\002\000\052\013\uffd9\014\uffd9\016\uffd9\017\uffd9\036\uffd9" +
    "\040\uffd9\051\uffd9\055\uffd9\056\uffd9\060\uffd9\061\uffd9\062" +
    "\uffd9\063\uffd9\064\uffd9\066\uffd9\067\uffd9\070\uffd9\071\uffd9" +
    "\072\uffd9\073\uffd9\001\002\000\046\004\uffc2\005\uffc2\006" +
    "\uffc2\007\uffc2\010\uffc2\011\uffc2\012\uffc2\020\uffc2\024\uffc2" +
    "\026\064\027\061\030\065\031\072\032\062\033\073\034" +
    "\056\035\uffc2\065\uffc2\001\002\000\032\004\uffc4\005\uffc4" +
    "\006\uffc4\007\uffc4\010\uffc4\011\uffc4\012\uffc4\020\uffc4\024" +
    "\uffc4\034\uffc4\035\uffc4\065\uffc4\001\002\000\032\004\uffc6" +
    "\005\uffc6\006\uffc6\007\uffc6\010\uffc6\011\uffc6\012\uffc6\020" +
    "\uffc6\024\uffc6\034\uffc6\035\uffc6\065\uffc6\001\002\000\046" +
    "\004\uffcf\005\uffcf\006\063\007\067\010\070\011\066\012" +
    "\057\020\uffcf\024\uffcf\026\064\027\061\030\065\031\072" +
    "\032\062\033\073\034\056\035\074\065\uffcf\001\002\000" +
    "\046\004\uffcc\005\uffcc\006\uffcc\007\uffcc\010\uffcc\011\066" +
    "\012\057\020\uffcc\024\uffcc\026\064\027\061\030\065\031" +
    "\072\032\062\033\073\034\056\035\074\065\uffcc\001\002" +
    "\000\046\004\uffcd\005\uffcd\006\uffcd\007\uffcd\010\070\011" +
    "\066\012\057\020\uffcd\024\uffcd\026\064\027\061\030\065" +
    "\031\072\032\062\033\073\034\056\035\074\065\uffcd\001" +
    "\002\000\046\004\uffcb\005\uffcb\006\uffcb\007\uffcb\010\uffcb" +
    "\011\uffcb\012\057\020\uffcb\024\uffcb\026\064\027\061\030" +
    "\065\031\072\032\062\033\073\034\056\035\074\065\uffcb" +
    "\001\002\000\032\004\uffc7\005\uffc7\006\uffc7\007\uffc7\010" +
    "\uffc7\011\uffc7\012\uffc7\020\uffc7\024\uffc7\034\uffc7\035\uffc7" +
    "\065\uffc7\001\002\000\032\004\uffc9\005\uffc9\006\uffc9\007" +
    "\uffc9\010\uffc9\011\uffc9\012\uffc9\020\uffc9\024\uffc9\034\uffc9" +
    "\035\uffc9\065\uffc9\001\002\000\046\004\uffce\005\uffce\006" +
    "\uffce\007\067\010\070\011\066\012\057\020\uffce\024\uffce" +
    "\026\064\027\061\030\065\031\072\032\062\033\073\034" +
    "\056\035\074\065\uffce\001\002\000\032\004\uffc5\005\uffc5" +
    "\006\uffc5\007\uffc5\010\uffc5\011\uffc5\012\uffc5\020\uffc5\024" +
    "\uffc5\034\uffc5\035\uffc5\065\uffc5\001\002\000\032\004\uffc8" +
    "\005\uffc8\006\uffc8\007\uffc8\010\uffc8\011\uffc8\012\uffc8\020" +
    "\uffc8\024\uffc8\034\uffc8\035\uffc8\065\uffc8\001\002\000\046" +
    "\004\uffd0\005\uffd0\006\063\007\067\010\070\011\066\012" +
    "\057\020\uffd0\024\uffd0\026\064\027\061\030\065\031\072" +
    "\032\062\033\073\034\056\035\074\065\uffd0\001\002\000" +
    "\046\004\uffca\005\uffca\006\uffca\007\uffca\010\uffca\011\uffca" +
    "\012\057\020\uffca\024\uffca\026\064\027\061\030\065\031" +
    "\072\032\062\033\073\034\056\035\074\065\uffca\001\002" +
    "\000\046\004\uffc3\005\uffc3\006\uffc3\007\uffc3\010\uffc3\011" +
    "\uffc3\012\uffc3\020\uffc3\024\uffc3\026\064\027\061\030\065" +
    "\031\072\032\062\033\073\034\uffc3\035\uffc3\065\uffc3\001" +
    "\002\000\046\004\uffbf\005\uffbf\006\uffbf\007\uffbf\010\uffbf" +
    "\011\uffbf\012\uffbf\020\uffbf\024\uffbf\026\uffbf\027\uffbf\030" +
    "\uffbf\031\uffbf\032\uffbf\033\uffbf\034\uffbf\035\uffbf\065\uffbf" +
    "\001\002\000\004\073\117\001\002\000\004\025\126\001" +
    "\002\000\026\013\035\014\052\017\044\036\030\066\036" +
    "\067\051\070\037\071\043\072\031\073\055\001\002\000" +
    "\042\004\060\005\071\006\063\007\067\010\070\011\066" +
    "\012\057\026\064\027\061\030\065\031\072\032\062\033" +
    "\073\034\056\035\074\065\122\001\002\000\026\013\035" +
    "\014\052\017\044\036\030\066\036\067\051\070\037\071" +
    "\043\072\031\073\055\001\002\000\042\004\060\005\071" +
    "\006\063\007\067\010\070\011\066\012\057\020\124\026" +
    "\064\027\061\030\065\031\072\032\062\033\073\034\056" +
    "\035\074\001\002\000\004\015\021\001\002\000\052\013" +
    "\uffdd\014\uffdd\016\uffdd\017\uffdd\036\uffdd\040\uffdd\051\uffdd" +
    "\055\uffdd\056\uffdd\060\uffdd\061\uffdd\062\uffdd\063\uffdd\064" +
    "\uffdd\066\uffdd\067\uffdd\070\uffdd\071\uffdd\072\uffdd\073\uffdd" +
    "\001\002\000\026\013\035\014\052\017\044\036\030\066" +
    "\036\067\051\070\037\071\043\072\031\073\055\001\002" +
    "\000\042\004\060\005\071\006\063\007\067\010\070\011" +
    "\066\012\057\026\064\027\061\030\065\031\072\032\062" +
    "\033\073\034\056\035\074\065\130\001\002\000\052\013" +
    "\uffe3\014\uffe3\016\uffe3\017\uffe3\036\uffe3\040\uffe3\051\uffe3" +
    "\055\uffe3\056\uffe3\060\uffe3\061\uffe3\062\uffe3\063\uffe3\064" +
    "\uffe3\066\uffe3\067\uffe3\070\uffe3\071\uffe3\072\uffe3\073\uffe3" +
    "\001\002\000\042\004\060\005\071\006\063\007\067\010" +
    "\070\011\066\012\057\020\132\026\064\027\061\030\065" +
    "\031\072\032\062\033\073\034\056\035\074\001\002\000" +
    "\046\004\uffbe\005\uffbe\006\uffbe\007\uffbe\010\uffbe\011\uffbe" +
    "\012\uffbe\020\uffbe\024\uffbe\026\uffbe\027\uffbe\030\uffbe\031" +
    "\uffbe\032\uffbe\033\uffbe\034\uffbe\035\uffbe\065\uffbe\001\002" +
    "\000\052\013\uffdb\014\uffdb\016\uffdb\017\uffdb\036\uffdb\040" +
    "\uffdb\051\uffdb\055\uffdb\056\uffdb\060\uffdb\061\uffdb\062\uffdb" +
    "\063\uffdb\064\uffdb\066\uffdb\067\uffdb\070\uffdb\071\uffdb\072" +
    "\uffdb\073\uffdb\001\002\000\046\004\uffc0\005\uffc0\006\uffc0" +
    "\007\uffc0\010\uffc0\011\uffc0\012\uffc0\020\uffc0\024\uffc0\026" +
    "\uffc0\027\uffc0\030\uffc0\031\uffc0\032\uffc0\033\uffc0\034\uffc0" +
    "\035\uffc0\065\uffc0\001\002\000\026\013\035\014\052\017" +
    "\044\036\030\066\036\067\051\070\037\071\043\072\031" +
    "\073\055\001\002\000\032\013\035\014\052\017\044\036" +
    "\030\053\144\054\uffd5\066\036\067\051\070\037\071\043" +
    "\072\031\073\055\001\002\000\032\013\uffd8\014\uffd8\017" +
    "\uffd8\036\uffd8\053\uffd8\054\uffd8\066\uffd8\067\uffd8\070\uffd8" +
    "\071\uffd8\072\uffd8\073\uffd8\001\002\000\042\004\060\005" +
    "\071\006\063\007\067\010\070\011\066\012\057\024\141" +
    "\026\064\027\061\030\065\031\072\032\062\033\073\034" +
    "\056\035\074\001\002\000\004\015\021\001\002\000\032" +
    "\013\uffd6\014\uffd6\017\uffd6\036\uffd6\053\uffd6\054\uffd6\066" +
    "\uffd6\067\uffd6\070\uffd6\071\uffd6\072\uffd6\073\uffd6\001\002" +
    "\000\004\054\150\001\002\000\004\024\146\001\002\000" +
    "\032\013\uffd7\014\uffd7\017\uffd7\036\uffd7\053\uffd7\054\uffd7" +
    "\066\uffd7\067\uffd7\070\uffd7\071\uffd7\072\uffd7\073\uffd7\001" +
    "\002\000\004\015\021\001\002\000\004\054\uffd4\001\002" +
    "\000\004\051\151\001\002\000\004\065\152\001\002\000" +
    "\052\013\uffdf\014\uffdf\016\uffdf\017\uffdf\036\uffdf\040\uffdf" +
    "\051\uffdf\055\uffdf\056\uffdf\060\uffdf\061\uffdf\062\uffdf\063" +
    "\uffdf\064\uffdf\066\uffdf\067\uffdf\070\uffdf\071\uffdf\072\uffdf" +
    "\073\uffdf\001\002\000\042\004\060\005\071\006\063\007" +
    "\067\010\070\011\066\012\057\026\064\027\061\030\065" +
    "\031\072\032\062\033\073\034\056\035\074\065\154\001" +
    "\002\000\052\013\uffdc\014\uffdc\016\uffdc\017\uffdc\036\uffdc" +
    "\040\uffdc\051\uffdc\055\uffdc\056\uffdc\060\uffdc\061\uffdc\062" +
    "\uffdc\063\uffdc\064\uffdc\066\uffdc\067\uffdc\070\uffdc\071\uffdc" +
    "\072\uffdc\073\uffdc\001\002\000\046\004\060\005\071\006" +
    "\063\007\067\010\070\011\066\012\057\020\uffc1\024\uffc1" +
    "\026\064\027\061\030\065\031\072\032\062\033\073\034" +
    "\056\035\074\065\uffc1\001\002\000\004\073\uffef\001\002" +
    "\000\004\073\164\001\002\000\004\073\uffee\001\002\000" +
    "\004\073\ufff0\001\002\000\004\073\uffed\001\002\000\004" +
    "\073\ufff1\001\002\000\010\022\170\025\167\065\165\001" +
    "\002\000\052\013\uffe7\014\uffe7\016\uffe7\017\uffe7\036\uffe7" +
    "\040\uffe7\051\uffe7\055\uffe7\056\uffe7\060\uffe7\061\uffe7\062" +
    "\uffe7\063\uffe7\064\uffe7\066\uffe7\067\uffe7\070\uffe7\071\uffe7" +
    "\072\uffe7\073\uffe7\001\002\000\006\025\201\065\200\001" +
    "\002\000\026\013\035\014\052\017\044\036\030\066\036" +
    "\067\051\070\037\071\043\072\031\073\055\001\002\000" +
    "\004\066\171\001\002\000\004\021\172\001\002\000\004" +
    "\022\173\001\002\000\004\066\174\001\002\000\004\021" +
    "\175\001\002\000\012\025\uffbb\037\uffbb\041\uffbb\065\uffbb" +
    "\001\002\000\042\004\060\005\071\006\063\007\067\010" +
    "\070\011\066\012\057\026\064\027\061\030\065\031\072" +
    "\032\062\033\073\034\056\035\074\065\177\001\002\000" +
    "\052\013\uffe6\014\uffe6\016\uffe6\017\uffe6\036\uffe6\040\uffe6" +
    "\051\uffe6\055\uffe6\056\uffe6\060\uffe6\061\uffe6\062\uffe6\063" +
    "\uffe6\064\uffe6\066\uffe6\067\uffe6\070\uffe6\071\uffe6\072\uffe6" +
    "\073\uffe6\001\002\000\052\013\uffe5\014\uffe5\016\uffe5\017" +
    "\uffe5\036\uffe5\040\uffe5\051\uffe5\055\uffe5\056\uffe5\060\uffe5" +
    "\061\uffe5\062\uffe5\063\uffe5\064\uffe5\066\uffe5\067\uffe5\070" +
    "\uffe5\071\uffe5\072\uffe5\073\uffe5\001\002\000\004\015\203" +
    "\001\002\000\004\065\217\001\002\000\004\015\204\001" +
    "\002\000\014\066\036\067\051\070\037\071\043\072\031" +
    "\001\002\000\006\016\210\023\207\001\002\000\006\016" +
    "\uffb8\023\uffb8\001\002\000\004\015\204\001\002\000\010" +
    "\037\uffba\041\uffba\065\uffba\001\002\000\006\016\uffb9\023" +
    "\uffb9\001\002\000\006\016\uffb5\023\uffb5\001\002\000\006" +
    "\016\215\023\214\001\002\000\014\066\036\067\051\070" +
    "\037\071\043\072\031\001\002\000\006\016\uffb7\023\uffb7" +
    "\001\002\000\006\016\uffb6\023\uffb6\001\002\000\052\013" +
    "\uffe4\014\uffe4\016\uffe4\017\uffe4\036\uffe4\040\uffe4\051\uffe4" +
    "\055\uffe4\056\uffe4\060\uffe4\061\uffe4\062\uffe4\063\uffe4\064" +
    "\uffe4\066\uffe4\067\uffe4\070\uffe4\071\uffe4\072\uffe4\073\uffe4" +
    "\001\002\000\042\004\060\005\071\006\063\007\067\010" +
    "\070\011\066\012\057\026\064\027\061\030\065\031\072" +
    "\032\062\033\073\034\056\035\074\065\221\001\002\000" +
    "\052\013\uffda\014\uffda\016\uffda\017\uffda\036\uffda\040\uffda" +
    "\051\uffda\055\uffda\056\uffda\060\uffda\061\uffda\062\uffda\063" +
    "\uffda\064\uffda\066\uffda\067\uffda\070\uffda\071\uffda\072\uffda" +
    "\073\uffda\001\002\000\050\013\035\014\052\017\044\036" +
    "\030\040\027\051\033\055\025\056\223\060\050\061\032" +
    "\062\042\063\026\064\053\066\036\067\051\070\037\071" +
    "\043\072\031\073\045\001\002\000\004\057\224\001\002" +
    "\000\026\013\035\014\052\017\044\036\030\066\036\067" +
    "\051\070\037\071\043\072\031\073\055\001\002\000\042" +
    "\004\060\005\071\006\063\007\067\010\070\011\066\012" +
    "\057\026\064\027\061\030\065\031\072\032\062\033\073" +
    "\034\056\035\074\065\226\001\002\000\004\054\227\001" +
    "\002\000\004\055\230\001\002\000\004\065\231\001\002" +
    "\000\052\013\uffde\014\uffde\016\uffde\017\uffde\036\uffde\040" +
    "\uffde\051\uffde\055\uffde\056\uffde\060\uffde\061\uffde\062\uffde" +
    "\063\uffde\064\uffde\066\uffde\067\uffde\070\uffde\071\uffde\072" +
    "\uffde\073\uffde\001\002\000\052\013\uffe0\014\uffe0\016\uffe0" +
    "\017\uffe0\036\uffe0\040\uffe0\051\uffe0\055\uffe0\056\uffe0\060" +
    "\uffe0\061\uffe0\062\uffe0\063\uffe0\064\uffe0\066\uffe0\067\uffe0" +
    "\070\uffe0\071\uffe0\072\uffe0\073\uffe0\001\002\000\004\073" +
    "\234\001\002\000\010\022\170\025\237\065\235\001\002" +
    "\000\006\037\ufffd\041\ufffd\001\002\000\010\025\242\037" +
    "\ufffb\041\ufffb\001\002\000\026\013\035\014\052\017\044" +
    "\036\030\066\036\067\051\070\037\071\043\072\031\073" +
    "\055\001\002\000\042\004\060\005\071\006\063\007\067" +
    "\010\070\011\066\012\057\026\064\027\061\030\065\031" +
    "\072\032\062\033\073\034\056\035\074\065\241\001\002" +
    "\000\006\037\ufffc\041\ufffc\001\002\000\004\015\203\001" +
    "\002\000\006\037\ufffa\041\ufffa\001\002\000\004\073\245" +
    "\001\002\000\004\017\246\001\002\000\016\020\252\044" +
    "\163\045\161\046\160\047\162\050\156\001\002\000\004" +
    "\015\021\001\002\000\006\041\ufff6\043\ufff6\001\002\000" +
    "\004\073\260\001\002\000\004\015\ufff5\001\002\000\006" +
    "\020\255\023\254\001\002\000\014\044\163\045\161\046" +
    "\160\047\162\050\156\001\002\000\004\015\ufff4\001\002" +
    "\000\004\073\257\001\002\000\006\020\ufff2\023\ufff2\001" +
    "\002\000\006\020\ufff3\023\ufff3\001\002\000\004\002\000" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\257\000\006\002\003\004\004\001\001\000\002\001" +
    "\001\000\010\003\011\005\007\007\010\001\001\000\004" +
    "\011\243\001\001\000\004\011\232\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\006\012\007\013\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\022\021\001\001" +
    "\000\004\021\022\001\001\000\002\001\001\000\014\012" +
    "\045\013\040\014\033\015\037\023\023\001\001\000\002" +
    "\001\001\000\004\021\221\001\001\000\006\012\045\023" +
    "\217\001\001\000\004\011\156\001\001\000\006\012\045" +
    "\023\154\001\001\000\002\001\001\000\006\012\045\023" +
    "\152\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\012\045\023\130\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\012\045\023\053\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\012\045" +
    "\023\113\001\001\000\006\012\045\023\112\001\001\000" +
    "\006\012\045\023\111\001\001\000\006\012\045\023\110" +
    "\001\001\000\006\012\045\023\107\001\001\000\006\012" +
    "\045\023\106\001\001\000\006\012\045\023\105\001\001" +
    "\000\006\012\045\023\104\001\001\000\006\012\045\023" +
    "\103\001\001\000\006\012\045\023\102\001\001\000\006" +
    "\012\045\023\101\001\001\000\006\012\045\023\100\001" +
    "\001\000\006\012\045\023\077\001\001\000\006\012\045" +
    "\023\076\001\001\000\006\012\045\023\075\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\014\117\001\001\000\002\001\001\000" +
    "\006\012\045\023\120\001\001\000\002\001\001\000\006" +
    "\012\045\023\122\001\001\000\002\001\001\000\004\022" +
    "\124\001\001\000\002\001\001\000\006\012\045\023\126" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\012\045\016\135\017\136\023\137\001\001\000" +
    "\012\012\045\017\144\020\142\023\137\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\022\141\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\022\146\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\024\165\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\012\045" +
    "\023\175\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\025\201\001\001\000\002\001\001\000\006" +
    "\027\204\030\205\001\001\000\006\012\211\031\212\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\030\210" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\012\215\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\012\045\013\040\014\033" +
    "\015\037\023\023\001\001\000\002\001\001\000\006\012" +
    "\045\023\224\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\024\235\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\012\045\023" +
    "\237\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\025\242\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\010\246\001\001\000\006\011\250\026\252\001\001" +
    "\000\004\022\247\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\011\255" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {

  return getScanner().next_token();

    }


    public void syntax_error(Symbol s){
        System.out.println("Error de sintaxis: "+ s.value +" Línea "+(s.left)+" Columna "+(s.right) );
    }
    public void unrecovered_syntax_error(Symbol s) throws Exception {
        Symbol t = getScanner().next_token();
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= globales funciones main 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // globales ::= globales global 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("globales",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // globales ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("globales",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // global ::= WORD tipo IDENTIFICADOR ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("global",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // global ::= WORD tipo IDENTIFICADOR ASIGNAR expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("global",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // global ::= WORD tipo IDENTIFICADOR Arreglo 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("global",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // global ::= WORD tipo IDENTIFICADOR Arreglo ASIGNAR BloqueArreglo 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("global",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // main ::= COAL NAVIDAD PARENTESIS_A PARENTESIS_B bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("main",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // funciones ::= funcion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // funciones ::= funciones funcion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // funcion ::= GIFT tipo IDENTIFICADOR params bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // params ::= PARENTESIS_A PARENTESIS_B 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("params",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // params ::= PARENTESIS_A itemParams PARENTESIS_B 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("params",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // itemParams ::= tipo IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("itemParams",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // itemParams ::= itemParams COMA tipo IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("itemParams",20, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // tipo ::= INT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipo ::= FLOAT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipo ::= STRING 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipo ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo ::= CHAR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // literal ::= INT_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // literal ::= FLOAT_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // literal ::= STRING_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // literal ::= CHAR_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // literal ::= BOOLEAN_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // creacion ::= LOCAL tipo IDENTIFICADOR ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("creacion",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // creacion ::= LOCAL tipo IDENTIFICADOR ASIGNAR expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("creacion",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // creacion ::= LOCAL tipo IDENTIFICADOR Arreglo ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("creacion",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // creacion ::= LOCAL tipo IDENTIFICADOR Arreglo ASIGNAR BloqueArreglo ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("creacion",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // asignacion ::= IDENTIFICADOR ASIGNAR expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentencia ::= creacion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sentencia ::= asignacion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // sentencia ::= expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // sentencia ::= DECIDE OF condiciones else_opcional END DECIDE ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // sentencia ::= LOOP sentencias EXIT WHEN expr ENDL END LOOP ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // sentencia ::= FOR PARENTESIS_A asignacion expr ENDL expr PARENTESIS_B bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // sentencia ::= RETURN expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // sentencia ::= BREAK ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // sentencia ::= SHOW expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // sentencia ::= GET expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // condiciones ::= condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condiciones",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // condiciones ::= condiciones condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condiciones",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // condicion ::= expr FLECHA bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // else_opcional ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("else_opcional",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // else_opcional ::= ELSE FLECHA bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("else_opcional",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sentencias ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // sentencias ::= sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // bloque ::= BLOQUE_A sentencias BLOQUE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr SUMA expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= expr RESTA expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= expr MULTIPLICACION expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= expr DIVISION expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= expr DIVISION_ENTERA expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= expr MODULO expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= expr POTENCIA expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= expr MAYOR expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= expr MENOR expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= expr IGUAL expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= expr DIFERENTE expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= expr MAYOR_IGUAL expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= expr MENOR_IGUAL expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= expr AND expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= expr OR expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= NOT expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= AUMENTO IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr ::= DISMINUCION IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expr ::= PARENTESIS_A expr PARENTESIS_B 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expr ::= literal 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expr ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // Arreglo ::= LLAVE_A INT_LITERAL LLAVE_B LLAVE_A INT_LITERAL LLAVE_B 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Arreglo",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // BloqueArreglo ::= BLOQUE_A Columnas BLOQUE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("BloqueArreglo",19, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // Columnas ::= Columnas COMA filas 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Columnas",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // Columnas ::= filas 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Columnas",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // filas ::= BLOQUE_A L_elementos BLOQUE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("filas",22, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // L_elementos ::= L_elementos COMA literal 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("L_elementos",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // L_elementos ::= literal 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("L_elementos",23, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
