
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\104\000\002\002\005\000\002\002\004\000\002\004" +
    "\004\000\002\004\002\000\002\005\006\000\002\005\010" +
    "\000\002\006\007\000\002\003\003\000\002\003\004\000" +
    "\002\007\007\000\002\010\004\000\002\010\005\000\002" +
    "\027\004\000\002\027\006\000\002\011\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\012\003\000\002\012\003\000\002\012\003\000" +
    "\002\012\003\000\002\012\003\000\002\013\006\000\002" +
    "\013\010\000\002\014\006\000\002\015\003\000\002\015" +
    "\003\000\002\015\004\000\002\015\011\000\002\015\013" +
    "\000\002\015\013\000\002\015\005\000\002\015\004\000" +
    "\002\015\005\000\002\015\005\000\002\016\003\000\002" +
    "\016\004\000\002\017\005\000\002\020\002\000\002\020" +
    "\005\000\002\021\002\000\002\021\004\000\002\022\005" +
    "\000\002\023\005\000\002\023\005\000\002\023\005\000" +
    "\002\023\005\000\002\023\005\000\002\023\005\000\002" +
    "\023\005\000\002\023\005\000\002\023\005\000\002\023" +
    "\005\000\002\023\005\000\002\023\005\000\002\023\005" +
    "\000\002\023\005\000\002\023\005\000\002\023\004\000" +
    "\002\023\004\000\002\023\004\000\002\023\005\000\002" +
    "\023\003\000\002\023\003\000\002\023\003\000\002\024" +
    "\007" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\234\000\006\035\ufffe\037\ufffe\001\002\000\004\002" +
    "\236\001\002\000\006\035\007\037\006\001\002\000\014" +
    "\042\027\043\047\044\044\045\030\046\045\001\002\000" +
    "\014\042\027\043\047\044\044\045\030\046\045\001\002" +
    "\000\006\035\uffff\037\uffff\001\002\000\006\037\ufffa\041" +
    "\ufffa\001\002\000\006\037\006\041\015\001\002\000\004" +
    "\002\001\001\002\000\006\037\ufff9\041\ufff9\001\002\000" +
    "\004\040\016\001\002\000\004\017\017\001\002\000\004" +
    "\020\020\001\002\000\004\015\021\001\002\000\062\013" +
    "\uffd7\014\uffd7\016\uffd7\017\uffd7\034\uffd7\036\uffd7\042\uffd7" +
    "\043\uffd7\044\uffd7\045\uffd7\046\uffd7\047\uffd7\053\uffd7\056" +
    "\uffd7\057\uffd7\060\uffd7\061\uffd7\062\uffd7\064\uffd7\065\uffd7" +
    "\066\uffd7\067\uffd7\070\uffd7\071\uffd7\001\002\000\004\002" +
    "\ufffb\001\002\000\062\013\041\014\061\016\056\017\053" +
    "\034\034\036\033\042\027\043\047\044\044\045\030\046" +
    "\045\047\037\053\031\056\060\057\036\060\051\061\032" +
    "\062\062\064\043\065\057\066\042\067\052\070\035\071" +
    "\054\001\002\000\046\004\uffbf\005\uffbf\006\uffbf\007\uffbf" +
    "\010\uffbf\011\uffbf\012\uffbf\020\uffbf\022\uffbf\024\uffbf\025" +
    "\uffbf\026\uffbf\027\uffbf\030\uffbf\031\uffbf\032\uffbf\033\uffbf" +
    "\063\uffbf\001\002\000\004\071\207\001\002\000\042\004" +
    "\070\005\100\006\072\007\076\010\077\011\074\012\066" +
    "\024\073\025\067\026\075\027\101\030\071\031\103\032" +
    "\065\033\102\063\206\001\002\000\004\071\ufff3\001\002" +
    "\000\004\071\uffef\001\002\000\062\013\uffd7\014\uffd7\017" +
    "\uffd7\034\uffd7\036\uffd7\042\uffd7\043\uffd7\044\uffd7\045\uffd7" +
    "\046\uffd7\047\uffd7\053\uffd7\054\uffd7\056\uffd7\057\uffd7\060" +
    "\uffd7\061\uffd7\062\uffd7\064\uffd7\065\uffd7\066\uffd7\067\uffd7" +
    "\070\uffd7\071\uffd7\001\002\000\040\013\041\014\061\017" +
    "\053\034\034\042\027\043\047\044\044\045\030\046\045" +
    "\064\043\065\057\066\042\067\052\070\035\071\064\001" +
    "\002\000\014\042\027\043\047\044\044\045\030\046\045" +
    "\001\002\000\040\013\041\014\061\017\053\034\034\042" +
    "\027\043\047\044\044\045\030\046\045\064\043\065\057" +
    "\066\042\067\052\070\035\071\064\001\002\000\046\004" +
    "\uffea\005\uffea\006\uffea\007\uffea\010\uffea\011\uffea\012\uffea" +
    "\020\uffea\022\uffea\024\uffea\025\uffea\026\uffea\027\uffea\030" +
    "\uffea\031\uffea\032\uffea\033\uffea\063\uffea\001\002\000\040" +
    "\013\041\014\061\017\053\034\034\042\027\043\047\044" +
    "\044\045\030\046\045\064\043\065\057\066\042\067\052" +
    "\070\035\071\064\001\002\000\004\050\145\001\002\000" +
    "\064\013\uffe5\014\uffe5\016\uffe5\017\uffe5\034\uffe5\036\uffe5" +
    "\042\uffe5\043\uffe5\044\uffe5\045\uffe5\046\uffe5\047\uffe5\053" +
    "\uffe5\054\uffe5\056\uffe5\057\uffe5\060\uffe5\061\uffe5\062\uffe5" +
    "\064\uffe5\065\uffe5\066\uffe5\067\uffe5\070\uffe5\071\uffe5\001" +
    "\002\000\004\071\144\001\002\000\046\004\uffec\005\uffec" +
    "\006\uffec\007\uffec\010\uffec\011\uffec\012\uffec\020\uffec\022" +
    "\uffec\024\uffec\025\uffec\026\uffec\027\uffec\030\uffec\031\uffec" +
    "\032\uffec\033\uffec\063\uffec\001\002\000\046\004\uffee\005" +
    "\uffee\006\uffee\007\uffee\010\uffee\011\uffee\012\uffee\020\uffee" +
    "\022\uffee\024\uffee\025\uffee\026\uffee\027\uffee\030\uffee\031" +
    "\uffee\032\uffee\033\uffee\063\uffee\001\002\000\004\071\ufff0" +
    "\001\002\000\004\071\ufff1\001\002\000\064\013\uffd6\014" +
    "\uffd6\016\uffd6\017\uffd6\034\uffd6\036\uffd6\042\uffd6\043\uffd6" +
    "\044\uffd6\045\uffd6\046\uffd6\047\uffd6\053\uffd6\054\uffd6\056" +
    "\uffd6\057\uffd6\060\uffd6\061\uffd6\062\uffd6\064\uffd6\065\uffd6" +
    "\066\uffd6\067\uffd6\070\uffd6\071\uffd6\001\002\000\004\071" +
    "\ufff2\001\002\000\064\013\uffe6\014\uffe6\016\uffe6\017\uffe6" +
    "\034\uffe6\036\uffe6\042\uffe6\043\uffe6\044\uffe6\045\uffe6\046" +
    "\uffe6\047\uffe6\053\uffe6\054\uffe6\056\uffe6\057\uffe6\060\uffe6" +
    "\061\uffe6\062\uffe6\064\uffe6\065\uffe6\066\uffe6\067\uffe6\070" +
    "\uffe6\071\uffe6\001\002\000\004\063\143\001\002\000\046" +
    "\004\uffeb\005\uffeb\006\uffeb\007\uffeb\010\uffeb\011\uffeb\012" +
    "\uffeb\020\uffeb\022\uffeb\024\uffeb\025\uffeb\026\uffeb\027\uffeb" +
    "\030\uffeb\031\uffeb\032\uffeb\033\uffeb\063\uffeb\001\002\000" +
    "\040\013\041\014\061\017\053\034\034\042\027\043\047" +
    "\044\044\045\030\046\045\064\043\065\057\066\042\067" +
    "\052\070\035\071\064\001\002\000\044\004\uffc0\005\uffc0" +
    "\006\uffc0\007\uffc0\010\uffc0\011\uffc0\012\uffc0\023\136\024" +
    "\uffc0\025\uffc0\026\uffc0\027\uffc0\030\uffc0\031\uffc0\032\uffc0" +
    "\033\uffc0\063\uffc0\001\002\000\046\004\uffc1\005\uffc1\006" +
    "\uffc1\007\uffc1\010\uffc1\011\uffc1\012\uffc1\020\uffc1\022\uffc1" +
    "\024\uffc1\025\uffc1\026\uffc1\027\uffc1\030\uffc1\031\uffc1\032" +
    "\uffc1\033\uffc1\063\uffc1\001\002\000\076\002\uffd5\013\uffd5" +
    "\014\uffd5\016\uffd5\017\uffd5\034\uffd5\036\uffd5\037\uffd5\041" +
    "\uffd5\042\uffd5\043\uffd5\044\uffd5\045\uffd5\046\uffd5\047\uffd5" +
    "\051\uffd5\052\uffd5\053\uffd5\054\uffd5\056\uffd5\057\uffd5\060" +
    "\uffd5\061\uffd5\062\uffd5\064\uffd5\065\uffd5\066\uffd5\067\uffd5" +
    "\070\uffd5\071\uffd5\001\002\000\046\004\uffed\005\uffed\006" +
    "\uffed\007\uffed\010\uffed\011\uffed\012\uffed\020\uffed\022\uffed" +
    "\024\uffed\025\uffed\026\uffed\027\uffed\030\uffed\031\uffed\032" +
    "\uffed\033\uffed\063\uffed\001\002\000\004\017\125\001\002" +
    "\000\004\071\124\001\002\000\040\013\041\014\061\017" +
    "\053\034\034\042\027\043\047\044\044\045\030\046\045" +
    "\064\043\065\057\066\042\067\052\070\035\071\064\001" +
    "\002\000\042\004\070\005\100\006\072\007\076\010\077" +
    "\011\074\012\066\024\073\025\067\026\075\027\101\030" +
    "\071\031\103\032\065\033\102\063\104\001\002\000\046" +
    "\004\uffc0\005\uffc0\006\uffc0\007\uffc0\010\uffc0\011\uffc0\012" +
    "\uffc0\020\uffc0\022\uffc0\024\uffc0\025\uffc0\026\uffc0\027\uffc0" +
    "\030\uffc0\031\uffc0\032\uffc0\033\uffc0\063\uffc0\001\002\000" +
    "\040\013\041\014\061\017\053\034\034\042\027\043\047" +
    "\044\044\045\030\046\045\064\043\065\057\066\042\067" +
    "\052\070\035\071\064\001\002\000\040\013\041\014\061" +
    "\017\053\034\034\042\027\043\047\044\044\045\030\046" +
    "\045\064\043\065\057\066\042\067\052\070\035\071\064" +
    "\001\002\000\040\013\041\014\061\017\053\034\034\042" +
    "\027\043\047\044\044\045\030\046\045\064\043\065\057" +
    "\066\042\067\052\070\035\071\064\001\002\000\040\013" +
    "\041\014\061\017\053\034\034\042\027\043\047\044\044" +
    "\045\030\046\045\064\043\065\057\066\042\067\052\070" +
    "\035\071\064\001\002\000\040\013\041\014\061\017\053" +
    "\034\034\042\027\043\047\044\044\045\030\046\045\064" +
    "\043\065\057\066\042\067\052\070\035\071\064\001\002" +
    "\000\040\013\041\014\061\017\053\034\034\042\027\043" +
    "\047\044\044\045\030\046\045\064\043\065\057\066\042" +
    "\067\052\070\035\071\064\001\002\000\040\013\041\014" +
    "\061\017\053\034\034\042\027\043\047\044\044\045\030" +
    "\046\045\064\043\065\057\066\042\067\052\070\035\071" +
    "\064\001\002\000\040\013\041\014\061\017\053\034\034" +
    "\042\027\043\047\044\044\045\030\046\045\064\043\065" +
    "\057\066\042\067\052\070\035\071\064\001\002\000\040" +
    "\013\041\014\061\017\053\034\034\042\027\043\047\044" +
    "\044\045\030\046\045\064\043\065\057\066\042\067\052" +
    "\070\035\071\064\001\002\000\040\013\041\014\061\017" +
    "\053\034\034\042\027\043\047\044\044\045\030\046\045" +
    "\064\043\065\057\066\042\067\052\070\035\071\064\001" +
    "\002\000\040\013\041\014\061\017\053\034\034\042\027" +
    "\043\047\044\044\045\030\046\045\064\043\065\057\066" +
    "\042\067\052\070\035\071\064\001\002\000\040\013\041" +
    "\014\061\017\053\034\034\042\027\043\047\044\044\045" +
    "\030\046\045\064\043\065\057\066\042\067\052\070\035" +
    "\071\064\001\002\000\040\013\041\014\061\017\053\034" +
    "\034\042\027\043\047\044\044\045\030\046\045\064\043" +
    "\065\057\066\042\067\052\070\035\071\064\001\002\000" +
    "\040\013\041\014\061\017\053\034\034\042\027\043\047" +
    "\044\044\045\030\046\045\064\043\065\057\066\042\067" +
    "\052\070\035\071\064\001\002\000\040\013\041\014\061" +
    "\017\053\034\034\042\027\043\047\044\044\045\030\046" +
    "\045\064\043\065\057\066\042\067\052\070\035\071\064" +
    "\001\002\000\064\013\uffdd\014\uffdd\016\uffdd\017\uffdd\034" +
    "\uffdd\036\uffdd\042\uffdd\043\uffdd\044\uffdd\045\uffdd\046\uffdd" +
    "\047\uffdd\053\uffdd\054\uffdd\056\uffdd\057\uffdd\060\uffdd\061" +
    "\uffdd\062\uffdd\064\uffdd\065\uffdd\066\uffdd\067\uffdd\070\uffdd" +
    "\071\uffdd\001\002\000\032\004\uffc8\005\uffc8\006\uffc8\007" +
    "\uffc8\010\uffc8\011\uffc8\012\uffc8\020\uffc8\022\uffc8\032\uffc8" +
    "\033\uffc8\063\uffc8\001\002\000\046\004\uffc6\005\uffc6\006" +
    "\uffc6\007\uffc6\010\uffc6\011\uffc6\012\uffc6\020\uffc6\022\uffc6" +
    "\024\073\025\067\026\075\027\101\030\071\031\103\032" +
    "\065\033\uffc6\063\uffc6\001\002\000\032\004\uffca\005\uffca" +
    "\006\uffca\007\uffca\010\uffca\011\uffca\012\uffca\020\uffca\022" +
    "\uffca\032\uffca\033\uffca\063\uffca\001\002\000\046\004\uffd3" +
    "\005\uffd3\006\072\007\076\010\077\011\074\012\066\020" +
    "\uffd3\022\uffd3\024\073\025\067\026\075\027\101\030\071" +
    "\031\103\032\065\033\102\063\uffd3\001\002\000\046\004" +
    "\uffd0\005\uffd0\006\uffd0\007\uffd0\010\uffd0\011\074\012\066" +
    "\020\uffd0\022\uffd0\024\073\025\067\026\075\027\101\030" +
    "\071\031\103\032\065\033\102\063\uffd0\001\002\000\046" +
    "\004\uffd1\005\uffd1\006\uffd1\007\uffd1\010\077\011\074\012" +
    "\066\020\uffd1\022\uffd1\024\073\025\067\026\075\027\101" +
    "\030\071\031\103\032\065\033\102\063\uffd1\001\002\000" +
    "\032\004\uffcb\005\uffcb\006\uffcb\007\uffcb\010\uffcb\011\uffcb" +
    "\012\uffcb\020\uffcb\022\uffcb\032\uffcb\033\uffcb\063\uffcb\001" +
    "\002\000\046\004\uffcf\005\uffcf\006\uffcf\007\uffcf\010\uffcf" +
    "\011\uffcf\012\066\020\uffcf\022\uffcf\024\073\025\067\026" +
    "\075\027\101\030\071\031\103\032\065\033\102\063\uffcf" +
    "\001\002\000\032\004\uffcd\005\uffcd\006\uffcd\007\uffcd\010" +
    "\uffcd\011\uffcd\012\uffcd\020\uffcd\022\uffcd\032\uffcd\033\uffcd" +
    "\063\uffcd\001\002\000\046\004\uffd2\005\uffd2\006\uffd2\007" +
    "\076\010\077\011\074\012\066\020\uffd2\022\uffd2\024\073" +
    "\025\067\026\075\027\101\030\071\031\103\032\065\033" +
    "\102\063\uffd2\001\002\000\032\004\uffc9\005\uffc9\006\uffc9" +
    "\007\uffc9\010\uffc9\011\uffc9\012\uffc9\020\uffc9\022\uffc9\032" +
    "\uffc9\033\uffc9\063\uffc9\001\002\000\046\004\uffd4\005\uffd4" +
    "\006\072\007\076\010\077\011\074\012\066\020\uffd4\022" +
    "\uffd4\024\073\025\067\026\075\027\101\030\071\031\103" +
    "\032\065\033\102\063\uffd4\001\002\000\032\004\uffcc\005" +
    "\uffcc\006\uffcc\007\uffcc\010\uffcc\011\uffcc\012\uffcc\020\uffcc" +
    "\022\uffcc\032\uffcc\033\uffcc\063\uffcc\001\002\000\046\004" +
    "\uffce\005\uffce\006\uffce\007\uffce\010\uffce\011\uffce\012\066" +
    "\020\uffce\022\uffce\024\073\025\067\026\075\027\101\030" +
    "\071\031\103\032\065\033\102\063\uffce\001\002\000\046" +
    "\004\uffc7\005\uffc7\006\uffc7\007\uffc7\010\uffc7\011\uffc7\012" +
    "\uffc7\020\uffc7\022\uffc7\024\073\025\067\026\075\027\101" +
    "\030\071\031\103\032\uffc7\033\uffc7\063\uffc7\001\002\000" +
    "\046\004\uffc3\005\uffc3\006\uffc3\007\uffc3\010\uffc3\011\uffc3" +
    "\012\uffc3\020\uffc3\022\uffc3\024\uffc3\025\uffc3\026\uffc3\027" +
    "\uffc3\030\uffc3\031\uffc3\032\uffc3\033\uffc3\063\uffc3\001\002" +
    "\000\004\071\126\001\002\000\004\023\136\001\002\000" +
    "\004\063\130\001\002\000\040\013\041\014\061\017\053" +
    "\034\034\042\027\043\047\044\044\045\030\046\045\064" +
    "\043\065\057\066\042\067\052\070\035\071\064\001\002" +
    "\000\042\004\070\005\100\006\072\007\076\010\077\011" +
    "\074\012\066\024\073\025\067\026\075\027\101\030\071" +
    "\031\103\032\065\033\102\063\132\001\002\000\040\013" +
    "\041\014\061\017\053\034\034\042\027\043\047\044\044" +
    "\045\030\046\045\064\043\065\057\066\042\067\052\070" +
    "\035\071\064\001\002\000\042\004\070\005\100\006\072" +
    "\007\076\010\077\011\074\012\066\020\134\024\073\025" +
    "\067\026\075\027\101\030\071\031\103\032\065\033\102" +
    "\001\002\000\004\015\021\001\002\000\064\013\uffe1\014" +
    "\uffe1\016\uffe1\017\uffe1\034\uffe1\036\uffe1\042\uffe1\043\uffe1" +
    "\044\uffe1\045\uffe1\046\uffe1\047\uffe1\053\uffe1\054\uffe1\056" +
    "\uffe1\057\uffe1\060\uffe1\061\uffe1\062\uffe1\064\uffe1\065\uffe1" +
    "\066\uffe1\067\uffe1\070\uffe1\071\uffe1\001\002\000\014\064" +
    "\043\065\057\066\042\067\052\070\035\001\002\000\004" +
    "\063\140\001\002\000\066\013\uffe7\014\uffe7\016\uffe7\017" +
    "\uffe7\034\uffe7\036\uffe7\042\uffe7\043\uffe7\044\uffe7\045\uffe7" +
    "\046\uffe7\047\uffe7\053\uffe7\054\uffe7\056\uffe7\057\uffe7\060" +
    "\uffe7\061\uffe7\062\uffe7\063\uffe7\064\uffe7\065\uffe7\066\uffe7" +
    "\067\uffe7\070\uffe7\071\uffe7\001\002\000\042\004\070\005" +
    "\100\006\072\007\076\010\077\011\074\012\066\020\142" +
    "\024\073\025\067\026\075\027\101\030\071\031\103\032" +
    "\065\033\102\001\002\000\046\004\uffc2\005\uffc2\006\uffc2" +
    "\007\uffc2\010\uffc2\011\uffc2\012\uffc2\020\uffc2\022\uffc2\024" +
    "\uffc2\025\uffc2\026\uffc2\027\uffc2\030\uffc2\031\uffc2\032\uffc2" +
    "\033\uffc2\063\uffc2\001\002\000\064\013\uffdf\014\uffdf\016" +
    "\uffdf\017\uffdf\034\uffdf\036\uffdf\042\uffdf\043\uffdf\044\uffdf" +
    "\045\uffdf\046\uffdf\047\uffdf\053\uffdf\054\uffdf\056\uffdf\057" +
    "\uffdf\060\uffdf\061\uffdf\062\uffdf\064\uffdf\065\uffdf\066\uffdf" +
    "\067\uffdf\070\uffdf\071\uffdf\001\002\000\046\004\uffc4\005" +
    "\uffc4\006\uffc4\007\uffc4\010\uffc4\011\uffc4\012\uffc4\020\uffc4" +
    "\022\uffc4\024\uffc4\025\uffc4\026\uffc4\027\uffc4\030\uffc4\031" +
    "\uffc4\032\uffc4\033\uffc4\063\uffc4\001\002\000\040\013\041" +
    "\014\061\017\053\034\034\042\027\043\047\044\044\045" +
    "\030\046\045\064\043\065\057\066\042\067\052\070\035" +
    "\071\064\001\002\000\042\004\070\005\100\006\072\007" +
    "\076\010\077\011\074\012\066\022\161\024\073\025\067" +
    "\026\075\027\101\030\071\031\103\032\065\033\102\001" +
    "\002\000\044\013\uffdc\014\uffdc\017\uffdc\034\uffdc\042\uffdc" +
    "\043\uffdc\044\uffdc\045\uffdc\046\uffdc\051\uffdc\052\uffdc\064" +
    "\uffdc\065\uffdc\066\uffdc\067\uffdc\070\uffdc\071\uffdc\001\002" +
    "\000\044\013\041\014\061\017\053\034\034\042\027\043" +
    "\047\044\044\045\030\046\045\051\151\052\uffd9\064\043" +
    "\065\057\066\042\067\052\070\035\071\064\001\002\000" +
    "\004\022\157\001\002\000\044\013\uffdb\014\uffdb\017\uffdb" +
    "\034\uffdb\042\uffdb\043\uffdb\044\uffdb\045\uffdb\046\uffdb\051" +
    "\uffdb\052\uffdb\064\uffdb\065\uffdb\066\uffdb\067\uffdb\070\uffdb" +
    "\071\uffdb\001\002\000\004\052\154\001\002\000\004\047" +
    "\155\001\002\000\004\063\156\001\002\000\064\013\uffe3" +
    "\014\uffe3\016\uffe3\017\uffe3\034\uffe3\036\uffe3\042\uffe3\043" +
    "\uffe3\044\uffe3\045\uffe3\046\uffe3\047\uffe3\053\uffe3\054\uffe3" +
    "\056\uffe3\057\uffe3\060\uffe3\061\uffe3\062\uffe3\064\uffe3\065" +
    "\uffe3\066\uffe3\067\uffe3\070\uffe3\071\uffe3\001\002\000\004" +
    "\015\021\001\002\000\004\052\uffd8\001\002\000\004\015" +
    "\021\001\002\000\044\013\uffda\014\uffda\017\uffda\034\uffda" +
    "\042\uffda\043\uffda\044\uffda\045\uffda\046\uffda\051\uffda\052" +
    "\uffda\064\uffda\065\uffda\066\uffda\067\uffda\070\uffda\071\uffda" +
    "\001\002\000\042\004\070\005\100\006\072\007\076\010" +
    "\077\011\074\012\066\024\073\025\067\026\075\027\101" +
    "\030\071\031\103\032\065\033\102\063\164\001\002\000" +
    "\064\013\uffe0\014\uffe0\016\uffe0\017\uffe0\034\uffe0\036\uffe0" +
    "\042\uffe0\043\uffe0\044\uffe0\045\uffe0\046\uffe0\047\uffe0\053" +
    "\uffe0\054\uffe0\056\uffe0\057\uffe0\060\uffe0\061\uffe0\062\uffe0" +
    "\064\uffe0\065\uffe0\066\uffe0\067\uffe0\070\uffe0\071\uffe0\001" +
    "\002\000\046\004\070\005\100\006\072\007\076\010\077" +
    "\011\074\012\066\020\uffc5\022\uffc5\024\073\025\067\026" +
    "\075\027\101\030\071\031\103\032\065\033\102\063\uffc5" +
    "\001\002\000\004\071\167\001\002\000\006\023\171\063" +
    "\170\001\002\000\064\013\uffe9\014\uffe9\016\uffe9\017\uffe9" +
    "\034\uffe9\036\uffe9\042\uffe9\043\uffe9\044\uffe9\045\uffe9\046" +
    "\uffe9\047\uffe9\053\uffe9\054\uffe9\056\uffe9\057\uffe9\060\uffe9" +
    "\061\uffe9\062\uffe9\064\uffe9\065\uffe9\066\uffe9\067\uffe9\070" +
    "\uffe9\071\uffe9\001\002\000\040\013\041\014\061\017\053" +
    "\034\034\042\027\043\047\044\044\045\030\046\045\064" +
    "\043\065\057\066\042\067\052\070\035\071\064\001\002" +
    "\000\042\004\070\005\100\006\072\007\076\010\077\011" +
    "\074\012\066\024\073\025\067\026\075\027\101\030\071" +
    "\031\103\032\065\033\102\063\173\001\002\000\064\013" +
    "\uffe8\014\uffe8\016\uffe8\017\uffe8\034\uffe8\036\uffe8\042\uffe8" +
    "\043\uffe8\044\uffe8\045\uffe8\046\uffe8\047\uffe8\053\uffe8\054" +
    "\uffe8\056\uffe8\057\uffe8\060\uffe8\061\uffe8\062\uffe8\064\uffe8" +
    "\065\uffe8\066\uffe8\067\uffe8\070\uffe8\071\uffe8\001\002\000" +
    "\042\004\070\005\100\006\072\007\076\010\077\011\074" +
    "\012\066\024\073\025\067\026\075\027\101\030\071\031" +
    "\103\032\065\033\102\063\175\001\002\000\064\013\uffde" +
    "\014\uffde\016\uffde\017\uffde\034\uffde\036\uffde\042\uffde\043" +
    "\uffde\044\uffde\045\uffde\046\uffde\047\uffde\053\uffde\054\uffde" +
    "\056\uffde\057\uffde\060\uffde\061\uffde\062\uffde\064\uffde\065" +
    "\uffde\066\uffde\067\uffde\070\uffde\071\uffde\001\002\000\062" +
    "\013\041\014\061\017\053\034\034\036\033\042\027\043" +
    "\047\044\044\045\030\046\045\047\037\053\031\054\177" +
    "\056\060\057\036\060\051\061\032\062\062\064\043\065" +
    "\057\066\042\067\052\070\035\071\054\001\002\000\004" +
    "\055\200\001\002\000\040\013\041\014\061\017\053\034" +
    "\034\042\027\043\047\044\044\045\030\046\045\064\043" +
    "\065\057\066\042\067\052\070\035\071\064\001\002\000" +
    "\042\004\070\005\100\006\072\007\076\010\077\011\074" +
    "\012\066\024\073\025\067\026\075\027\101\030\071\031" +
    "\103\032\065\033\102\063\202\001\002\000\004\052\203" +
    "\001\002\000\004\053\204\001\002\000\004\063\205\001" +
    "\002\000\064\013\uffe2\014\uffe2\016\uffe2\017\uffe2\034\uffe2" +
    "\036\uffe2\042\uffe2\043\uffe2\044\uffe2\045\uffe2\046\uffe2\047" +
    "\uffe2\053\uffe2\054\uffe2\056\uffe2\057\uffe2\060\uffe2\061\uffe2" +
    "\062\uffe2\064\uffe2\065\uffe2\066\uffe2\067\uffe2\070\uffe2\071" +
    "\uffe2\001\002\000\064\013\uffe4\014\uffe4\016\uffe4\017\uffe4" +
    "\034\uffe4\036\uffe4\042\uffe4\043\uffe4\044\uffe4\045\uffe4\046" +
    "\uffe4\047\uffe4\053\uffe4\054\uffe4\056\uffe4\057\uffe4\060\uffe4" +
    "\061\uffe4\062\uffe4\064\uffe4\065\uffe4\066\uffe4\067\uffe4\070" +
    "\uffe4\071\uffe4\001\002\000\004\064\210\001\002\000\004" +
    "\064\211\001\002\000\004\063\212\001\002\000\046\004" +
    "\uffbe\005\uffbe\006\uffbe\007\uffbe\010\uffbe\011\uffbe\012\uffbe" +
    "\020\uffbe\022\uffbe\024\uffbe\025\uffbe\026\uffbe\027\uffbe\030" +
    "\uffbe\031\uffbe\032\uffbe\033\uffbe\063\uffbe\001\002\000\004" +
    "\071\214\001\002\000\006\023\216\063\215\001\002\000" +
    "\006\035\ufffd\037\ufffd\001\002\000\040\013\041\014\061" +
    "\017\053\034\034\042\027\043\047\044\044\045\030\046" +
    "\045\064\043\065\057\066\042\067\052\070\035\071\064" +
    "\001\002\000\042\004\070\005\100\006\072\007\076\010" +
    "\077\011\074\012\066\024\073\025\067\026\075\027\101" +
    "\030\071\031\103\032\065\033\102\063\220\001\002\000" +
    "\006\035\ufffc\037\ufffc\001\002\000\004\071\222\001\002" +
    "\000\004\017\223\001\002\000\016\020\227\042\027\043" +
    "\047\044\044\045\030\046\045\001\002\000\004\015\021" +
    "\001\002\000\006\037\ufff8\041\ufff8\001\002\000\004\071" +
    "\235\001\002\000\004\015\ufff7\001\002\000\006\020\232" +
    "\021\231\001\002\000\014\042\027\043\047\044\044\045" +
    "\030\046\045\001\002\000\004\015\ufff6\001\002\000\004" +
    "\071\234\001\002\000\006\020\ufff4\021\ufff4\001\002\000" +
    "\006\020\ufff5\021\ufff5\001\002\000\004\002\000\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\234\000\006\002\003\004\004\001\001\000\002\001" +
    "\001\000\010\003\011\005\007\007\010\001\001\000\004" +
    "\011\220\001\001\000\004\011\212\001\001\000\002\001" +
    "\001\000\002\001\001\000\006\006\012\007\013\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\022\021\001\001" +
    "\000\004\021\022\001\001\000\002\001\001\000\020\011" +
    "\024\012\054\013\047\014\037\015\045\023\025\024\023" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\021\175" +
    "\001\001\000\012\011\024\012\054\023\173\024\023\001" +
    "\001\000\004\011\165\001\001\000\012\011\024\012\054" +
    "\023\164\024\023\001\001\000\002\001\001\000\012\011" +
    "\024\012\054\023\162\024\023\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\011\024\012\054\023\140" +
    "\024\023\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\011\024\012\054\023\062\024\023\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\011\024" +
    "\012\054\023\122\024\023\001\001\000\012\011\024\012" +
    "\054\023\121\024\023\001\001\000\012\011\024\012\054" +
    "\023\120\024\023\001\001\000\012\011\024\012\054\023" +
    "\117\024\023\001\001\000\012\011\024\012\054\023\116" +
    "\024\023\001\001\000\012\011\024\012\054\023\115\024" +
    "\023\001\001\000\012\011\024\012\054\023\114\024\023" +
    "\001\001\000\012\011\024\012\054\023\113\024\023\001" +
    "\001\000\012\011\024\012\054\023\112\024\023\001\001" +
    "\000\012\011\024\012\054\023\111\024\023\001\001\000" +
    "\012\011\024\012\054\023\110\024\023\001\001\000\012" +
    "\011\024\012\054\023\107\024\023\001\001\000\012\011" +
    "\024\012\054\023\106\024\023\001\001\000\012\011\024" +
    "\012\054\023\105\024\023\001\001\000\012\011\024\012" +
    "\054\023\104\024\023\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\014" +
    "\126\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\011\024\012\054\023\130\024\023\001\001\000\002\001" +
    "\001\000\012\011\024\012\054\023\132\024\023\001\001" +
    "\000\002\001\001\000\004\022\134\001\001\000\002\001" +
    "\001\000\004\012\136\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\016\011\024\012\054\016\147" +
    "\017\146\023\145\024\023\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\011\024\012\054\017\151\020\152" +
    "\023\145\024\023\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\022\157\001\001\000\002\001" +
    "\001\000\004\022\161\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\011\024" +
    "\012\054\023\171\024\023\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\020" +
    "\011\024\012\054\013\047\014\037\015\045\023\025\024" +
    "\023\001\001\000\002\001\001\000\012\011\024\012\054" +
    "\023\200\024\023\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\011\024\012\054\023" +
    "\216\024\023\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\010\223\001\001\000\006\011" +
    "\225\027\227\001\001\000\004\022\224\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\232\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}


  /** Scan to get the next Symbol. */
  public java_cup.runtime.Symbol scan()
    throws java.lang.Exception
    {

  return getScanner().next_token();

    }


    public void syntax_error(Symbol s){
        System.out.println("Error de sintaxis: "+ s.value +" Línea "+(s.left+1)+" Columna "+(s.right+1) );
    }
    public void unrecovered_syntax_error(Symbol s) throws Exception {
        Symbol t = getScanner().next_token();
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action_part00000000(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= globales funciones main 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // globales ::= globales global 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("globales",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // globales ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("globales",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // global ::= WORD tipo IDENTIFICADOR ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("global",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // global ::= WORD tipo IDENTIFICADOR ASIGNAR expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("global",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // main ::= COAL NAVIDAD PARENTESIS_A PARENTESIS_B bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("main",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // funciones ::= funcion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // funciones ::= funciones funcion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funciones",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // funcion ::= GIFT tipo IDENTIFICADOR params bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("funcion",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // params ::= PARENTESIS_A PARENTESIS_B 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("params",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // params ::= PARENTESIS_A itemParams PARENTESIS_B 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("params",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // itemParams ::= tipo IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("itemParams",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // itemParams ::= itemParams COMA tipo IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("itemParams",21, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // tipo ::= INT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // tipo ::= FLOAT 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // tipo ::= STRING 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipo ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipo ::= CHAR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("tipo",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // literal ::= INT_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // literal ::= FLOAT_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // literal ::= STRING_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // literal ::= CHAR_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // literal ::= BOOLEAN_LITERAL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("literal",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // creacion ::= LOCAL tipo IDENTIFICADOR ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("creacion",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // creacion ::= LOCAL tipo IDENTIFICADOR ASIGNAR expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("creacion",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // asignacion ::= IDENTIFICADOR ASIGNAR literal ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("asignacion",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // sentencia ::= creacion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // sentencia ::= asignacion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // sentencia ::= expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // sentencia ::= DECIDE OF condiciones else_opcional END DECIDE ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // sentencia ::= LOOP sentencias EXIT WHEN expr ENDL END LOOP ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // sentencia ::= FOR PARENTESIS_A asignacion ENDL expr ENDL expr PARENTESIS_B bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // sentencia ::= RETURN expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // sentencia ::= BREAK ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // sentencia ::= SHOW expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // sentencia ::= GET expr ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencia",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // condiciones ::= condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condiciones",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // condiciones ::= condiciones condicion 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condiciones",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // condicion ::= expr FLECHA bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("condicion",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // else_opcional ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("else_opcional",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // else_opcional ::= ELSE FLECHA bloque 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("else_opcional",14, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // sentencias ::= 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // sentencias ::= sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("sentencias",15, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // bloque ::= BLOQUE_A sentencias BLOQUE_C 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("bloque",16, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // expr ::= expr SUMA expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expr ::= expr RESTA expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expr ::= expr MULTIPLICACION expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expr ::= expr DIVISION expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expr ::= expr DIVISION_ENTERA expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expr ::= expr MODULO expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expr ::= expr POTENCIA expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expr ::= expr MAYOR expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expr ::= expr MENOR expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expr ::= expr IGUAL expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expr ::= expr DIFERENTE expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expr ::= expr MAYOR_IGUAL expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expr ::= expr MENOR_IGUAL expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expr ::= expr AND expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr ::= expr OR expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr ::= NOT expr 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr ::= AUMENTO IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr ::= DISMINUCION IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= PARENTESIS_A expr PARENTESIS_B 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= literal 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr ::= Arreglo 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("expr",17, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // Arreglo ::= tipo IDENTIFICADOR INT_LITERAL INT_LITERAL ENDL 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("Arreglo",18, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
              return CUP$Parser$do_action_part00000000(
                               CUP$Parser$act_num,
                               CUP$Parser$parser,
                               CUP$Parser$stack,
                               CUP$Parser$top);
    }
}

}
