
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AUMENTO = 9;
  public static final int SHOW = 47;
  public static final int WHEN = 43;
  public static final int STRING_LITERAL = 52;
  public static final int ASIGNAR = 17;
  public static final int CHAR = 35;
  public static final int WORD = 27;
  public static final int CHAR_LITERAL = 53;
  public static final int BLOQUE_C = 12;
  public static final int DIFERENTE = 21;
  public static final int RESTA = 3;
  public static final int DIVISION_ENTERA = 6;
  public static final int BLOQUE_A = 11;
  public static final int INT = 32;
  public static final int FOR = 44;
  public static final int BOOLEAN_LITERAL = 54;
  public static final int IDENTIFICADOR = 55;
  public static final int ENDL = 49;
  public static final int NOT = 26;
  public static final int AND = 24;
  public static final int IGUAL = 20;
  public static final int DECIDE = 37;
  public static final int COAL = 31;
  public static final int OR = 25;
  public static final int GET = 48;
  public static final int NAVIDAD = 30;
  public static final int SUMA = 2;
  public static final int EXIT = 42;
  public static final int LOOP = 41;
  public static final int OF = 38;
  public static final int EOF = 0;
  public static final int BOOLEAN = 34;
  public static final int RETURN = 45;
  public static final int error = 1;
  public static final int COMA = 15;
  public static final int MODULO = 7;
  public static final int MENOR = 19;
  public static final int BREAK = 46;
  public static final int MAYOR = 18;
  public static final int POTENCIA = 8;
  public static final int FLECHA = 16;
  public static final int ELSE = 39;
  public static final int PARENTESIS_B = 14;
  public static final int PARENTESIS_A = 13;
  public static final int MAYOR_IGUAL = 22;
  public static final int FLOAT = 33;
  public static final int END = 40;
  public static final int STRING = 36;
  public static final int LOCAL = 28;
  public static final int DISMINUCION = 10;
  public static final int MENOR_IGUAL = 23;
  public static final int FLOAT_LITERAL = 51;
  public static final int DIVISION = 5;
  public static final int GIFT = 29;
  public static final int INT_LITERAL = 50;
  public static final int MULTIPLICACION = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "DIVISION_ENTERA",
  "MODULO",
  "POTENCIA",
  "AUMENTO",
  "DISMINUCION",
  "BLOQUE_A",
  "BLOQUE_C",
  "PARENTESIS_A",
  "PARENTESIS_B",
  "COMA",
  "FLECHA",
  "ASIGNAR",
  "MAYOR",
  "MENOR",
  "IGUAL",
  "DIFERENTE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "AND",
  "OR",
  "NOT",
  "WORD",
  "LOCAL",
  "GIFT",
  "NAVIDAD",
  "COAL",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "DECIDE",
  "OF",
  "ELSE",
  "END",
  "LOOP",
  "EXIT",
  "WHEN",
  "FOR",
  "RETURN",
  "BREAK",
  "SHOW",
  "GET",
  "ENDL",
  "INT_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "CHAR_LITERAL",
  "BOOLEAN_LITERAL",
  "IDENTIFICADOR"
  };
}

